[package]
name = "m5stamp-c3-pal"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
embedded-svc = "0.22"
esp-idf-svc = { version= "0.42", features = ["experimental", "alloc"] }
esp-idf-sys = { version = "0.31" }
log = "0.4"
pal = { path = "../pal" }