[package]
name = "m5stamp-c3-pal"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-idf-svc = { version= "0.42", features = ["experimental", "alloc"] }
embedded-svc = "0.22"
rgb = "0.8"
pal = { path = "../pal" }
m5stamp-c3-bsc = { path = "../m5stamp-c3-bsc" }